### ISSUE TITLE
Request for an invite

### ISSUE THREAD

**Issue by datakurre** [nix-community/nix-community.org#4]
Please, invite @johbo to nix-community. That would let @johbo to transfer the original repository of pip2nix here.

**Comment by zimbatm** [comment]
@johbo: you've been invited!

Let me know once the repository has been transferred so I can give you back admin on it. If you want to chat we have the #nix-community channel on IRC.

**Comment by datakurre** [comment]
<img width="571" alt="A9098927-A412-4129-B67C-0352E9F0C391" src="https://user-images.githubusercontent.com/160447/82811758-3041eb00-9e9a-11ea-9d8a-1b5b671ccf4a.png">

**Comment by Mic92** [comment]
@jhobo is not yet in the organisation. I sent him an invite and added him to a pip2nix team.

**Comment by Mic92** [comment]
https://dl.thalheim.io/6ZwUKaWUCWka9JO8tKPVTA/2020-05-25_14-38.png
